name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_job:
    uses: ./.github/workflows/build.yml  

  test_job:
    needs: build_job
    uses: ./.github/workflows/test.yml  
    with:
      build-artifact: "calculator-jar"

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-jar
          path: dist

      - name: Deploy
        run: |
          echo "Deploying artifact..."
          ls -la dist
